config/routes.rb
Gardy::Application.routes.draw do

  get "home/index"

  devise_for :members

  resources :members
  resources :schedules
  resources :attendance_lists

  root :to => 'home#index'

  match ':controller(/:action(:/id(.:format)))'

end

app/models/attendance_list.rb
class AttendanceList < ActiveRecord::Base
  attr_accessible :comment, :id, :member_id, :schedule_id, :status

  def self.select_insert_attendance_list(sche_id)
    sqlstr = "INSERT INTO attendance_lists (schedule_id, member_id, status, comment, created_at, updated_at) SELECT " + sche_id.to_s + ", id, 0, NULL, now(), now() FROM members;"
    return connection.execute(sqlstr)
  end

  def self.get_member_schedule(mem_id)
    sql = "SELECT al.schedule_id,al.member_id,al.status,al.comment,m.number,m.name_ja FROM attendance_lists AS al INNER JOIN schedules AS s ON al.schedule_id = s.id LEFT JOIN members AS m ON al.member_id=m.id WHERE al.member_id = ? AND s.kick_date > (CURDATE() - INTERVAL 2 DAY) ORDER BY s.kick_date;"
    return AttendanceList.find_by_sql([sql, mem_id.to_s])
  end

  def self.get_schedule_and_members(schedule_id)
    sql = "SELECT s.*, al.member_id, al.status AS attendance_stat, al.comment AS attendance_come, m.number,m.name_ja FROM attendance_lists AS al INNER JOIN schedules AS s ON al.schedule_id = s.id LEFT JOIN members AS m ON al.member_id=m.id WHERE al.schedule_id = ? ORDER BY m.number;"
    return AttendanceList.find_by_sql([sql, schedule_id.to_s])
  end

end

app/controllers/attendance_lists_controller.rb
class AttendanceListsController < ApplicationController

  before_filter :authenticate_member!

  # GET /attendance_lists
  # GET /attendance_lists.json
  def index

    @attendance_status = Constants.attendance_status

    #@attendance_lists = AttendanceList.all
    @schedules = Schedule.get_active_schedule()
    #logger.debug(@schedules)

    @attendance_lists = Array.new
    @schedules.each{|schedule|
      @attendance_list = AttendanceList.get_schedule_and_members(schedule.id)
      @attendance_lists << @attendance_list
    } 

    #@members = Member.where("status in (1,2)").order("id ASC").pluck(:id)
    #@members.each{|mem_id|
    #  ## SELECT
    #  @attendance_list = AttendanceList.get_member_schedule(mem_id)
    #  @attendance_lists << @attendance_list
    #}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schedules }
      format.json { render json: @attendance_lists }
    end
  end

  # GET /attendance_lists/1
  # GET /attendance_lists/1.json
  def show

    @attendance_status = Constants.attendance_status

    #@attendance_list = AttendanceList.find(params[:id])
    @attendance_list = AttendanceList.get_schedule_and_members(params[:id])
    logger.debug(@attendance_list)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attendance_list }
    end
  end

  # GET /attendance_lists/new
  # GET /attendance_lists/new.json
  def new
    @attendance_list = AttendanceList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attendance_list }
    end
  end

  # GET /attendance_lists/1/edit
  def edit
    @attendance_list = AttendanceList.find(params[:id])
  end

  # POST /attendance_lists
  # POST /attendance_lists.json
  def create
    @attendance_list = AttendanceList.new(params[:attendance_list])

    respond_to do |format|
      if @attendance_list.save
        format.html { redirect_to @attendance_list, notice: 'Attendance list was successfully created.' }
        format.json { render json: @attendance_list, status: :created, location: @attendance_list }
      else
        format.html { render action: "new" }
        format.json { render json: @attendance_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attendance_lists/1
  # PUT /attendance_lists/1.json
  def update
    @attendance_list = AttendanceList.find(params[:id])

    respond_to do |format|
      if @attendance_list.update_attributes(params[:attendance_list])
        format.html { redirect_to @attendance_list, notice: 'Attendance list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attendance_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendance_lists/1
  # DELETE /attendance_lists/1.json
  def destroy
    @attendance_list = AttendanceList.find(params[:id])
    @attendance_list.destroy

    respond_to do |format|
      format.html { redirect_to attendance_lists_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/attendance_lists_helper.rb
module AttendanceListsHelper
end

app/views/attendance_lists/_form.html.erb
<%= form_for(@attendance_list) do |f| %>
  <% if @attendance_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendance_list.errors.count, "error") %> prohibited this attendance_list from being saved:</h2>

      <ul>
      <% @attendance_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :schedule_id %><br />
    <%= f.number_field :schedule_id %>
  </div>
  <div class="field">
    <%= f.label :member_id %><br />
    <%= f.number_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendance_lists/edit.html.erb
<h1>Editing attendance_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendance_list %> |
<%= link_to 'Back', attendance_lists_path %>

app/views/attendance_lists/index.html.erb
<h1>Gardy</h1>
<h2>出欠表</h2>

<ul>
<% @schedules.each do |schedule| %>
  <li><a href="#<%= schedule.kick_date %>"><%= schedule.kick_date.strftime("%m/%d") %></a></li>
<% end %>
</ul>

<br />

<% @save_schedule_id="0" %>
<% @attendance_lists.each do |attendance_list| %>
  <% attendance_list.each do |list| %>
  <% if @save_schedule_id != list.id %>
  <hr />
  <ul id="<%= list.kick_date %>">
    <li><a href="/attendance_lists/<%= list.id %>"><h3>内容:[<%= list.title %>]</h3></a></li>
    <li>日時:<%= list.kick_date.strftime("%Y/%m/%d") %> <%= list.start_time.strftime("%H:%M") %>-<%= list.end_time.strftime("%H:%M") %></li>
    <li>場所:<%= list.place %></li>
    <li>詳細:<%= list.contents %></li>
  <ul/>
  <br />
  <% end %>
  <% @save_schedule_id=list.id %>
  <table>
  <tr>
    <td><b>・[<%= list.number %>]<%= list.name_ja %></b></td>
    <td><%= @attendance_status[list.attendance_stat] %><br /><%= (list.attendance_come) %></td>
    <td><%= link_to 'Edit', edit_attendance_list_path(list.member_id) %></td>
  </tr>
  </table>
  <% end %>
  <br />
  <br />
<% end %>

<br />
<!--
<%= link_to 'New Attendance list', new_attendance_list_path %>
-->

app/views/attendance_lists/new.html.erb
<h1>New attendance_list</h1>

<%= render 'form' %>

<%= link_to 'Back', attendance_lists_path %>

app/views/attendance_lists/show.html.erb
<p id="notice"><%= notice %></p>

<hr />
<% @save_schedule_id="0" %>
<% @attendance_list.each do |list| %>
  <% if @save_schedule_id != list.id %>
<h3>
  <b>内容:</b>
  <%= list.title %>
</h3>

<p>
  <b>日時:</b>
  <%= list.kick_date.strftime("%Y/%m/%d") %> <%= list.start_time.strftime("%H:%M") %>-<%= list.end_time.strftime("%H:%M") %>
</p>

<p>
  <b>場所:</b>
  <%= list.place %>
</p>

<p>
  <b>詳細:</b>
  <%= list.contents %>
</p>

<hr />
<% end %>
<% @save_schedule_id=list.id %>

<ul>
    <li><b>[<%= list.number %>]<%= list.name_ja %></b></li>
    <li><%= @attendance_status[list.attendance_stat] %><br /><%= (list.attendance_come) %></le>
</ul>
<% end %>

<%= link_to 'Edit', edit_attendance_list_path(@attendance_list) %> |
<%= link_to 'Back', attendance_lists_path %>