config/routes.rb
Gardy::Application.routes.draw do

  get "home/index"

  devise_for :members

  resources :members
  resources :schedules
  resources :attendance_lists

  root :to => 'home#index'

  match ':controller(/:action(:/id(.:format)))'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :contents, :end_time, :id, :kick_date, :open_flag, :register, :start_time, :title, :place

  def self.get_active_schedule()
    sql = "SELECT id, title, kick_date, start_time FROM schedules WHERE kick_date > (CURDATE() - INTERVAL 2 DAY) AND open_flag=1 ORDER BY kick_date;"
    return Schedule.find_by_sql([sql])
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  # GET /schedules
  # GET /schedules.json
  def index
    day=Time.now - 2.day
    #@schedules = Schedule.all
    @schedules = Schedule.where("kick_date >= ?", day).order("kick_date ASC") 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
        AttendanceList.select_insert_attendance_list(@schedule.id)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render json: @schedule, status: :created, location: @schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kick_date %> (開催日)<br />
    <%= f.date_select :kick_date, :order => [ :year, :month, :day ], :use_month_numbers => true, :locale => 'ja' %>
  </div>
  <div class="field">
    <%= f.label :start_time %> (開始時刻)<br />
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %> (終了時刻)<br />
    <%= f.time_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :place %> (場所)<br />
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :title %> (タイトル)<br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :contents %> (内容)<br />
    <%= f.text_area :contents %>
  </div>
  <div class="field">
    <%= f.label :open_flag %> (スケジュール公開フラグ)<br />
    <%= f.check_box :open_flag %>
  </div>
  <div class="field">
    <%= f.label :register %> (登録者)<br />
    <%= f.text_field :register %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/_list.html.erb
<%- if @schedules %>
<br />    
<p>
<table class="simple_table">
  <tr>
    <th>開催日</th>
    <th>時刻</th>
    <th>場所</th>
    <th>タイトル</th>
    <th>内容</th>
    <th>登録時刻</th>
  </tr>

<% @schedules.each do |schedule| %>
  <tr>
    <td><%= schedule.kick_date.strftime("%Y/%m/%d") %></td>
    <td><%= schedule.start_time.strftime("%H:%M") %> - <%= schedule.end_time.strftime("%H:%M") %></td>
    <td><%= schedule.place %></td>
    <td><%= schedule.title %></td>
    <td><%= schedule.contents %></td>
    <td><%= schedule.created_at.strftime("%Y/%m/%d %H:%M") %></td>
  </tr>
<% end %>
<% else%>
<div>直近の活動はありません。</div>
<% end -%>
</table>
</p>

app/views/schedules/edit.html.erb
<div class="page_title">
    <h2>A.C.GARDY Editing Schedule</h2>
</div>

<div class=“entry_main>

<%= render 'form' %>

<%= link_to '詳細参照', @schedule %> |
<%= link_to '一覧へ戻る', schedules_path %>
</div>

app/views/schedules/index.html.erb
<div class="page_title">
      <h2>A.C.GARDY Schedules</h2>
</div>

<div class="list_main">
<table class="simple_table">
  <tr>
    <th>ID</th>
    <th>開催日</th>
    <th>開始時刻</th>
    <th>終了時刻</th>
    <th>場所</th>
    <th>タイトル</th>
    <th>内容</th>
    <th>公開</th>
    <th>登録者</th>
    <th>登録日時</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schedules.each do |schedule| %>
  <tr>
    <td><%= schedule.id %></td>
    <td><%= schedule.kick_date.strftime("%Y/%m/%d") %></td>
    <td><%= schedule.start_time.strftime("%H:%M") %></td>
    <td><%= schedule.end_time.strftime("%H:%M") %></td>
    <td><%= schedule.place %></td>
    <td><%= schedule.title %></td>
    <td><%= schedule.contents %></td>
    <td><%= schedule.open_flag %></td>
    <td><%= schedule.register %></td>
    <td><%= schedule.kick_date.strftime("%Y/%m/%d %H:%M:%S") %></td>
    <td><%= link_to '詳細', schedule %></td>
    <td><%= link_to '編集', edit_schedule_path(schedule) %></td>
    <td><%= link_to '削除', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'スケジュール登録', new_schedule_path %>
</div>

app/views/schedules/new.html.erb
<div class="page_title">
    <h2>A.C. GARDY Schedule Registration</h2>
</div>

<div class="entry_main">

<%= render 'form' %>

<%= link_to '一覧へ戻る', schedules_path %>
</div>

app/views/schedules/show.html.erb
<div class="page_title">
    <h2>A.C.GARDY Schedules Detail</h2>
</div>

<div class="detail_main">

<p id="notice"><%= notice %></p>

<p>
  <b>ID:</b>
  <%= @schedule.id %>
</p>

<p>
  <b>Kick date (開催日):</b>
  <%= @schedule.kick_date.strftime("%Y/%m/%d") %>
</p>

<p>
  <b>Start time (開始時刻):</b>
  <%= @schedule.start_time.strftime("%H:%M") %>
</p>

<p>
  <b>End time (終了時刻):</b>
  <%= @schedule.end_time.strftime("%H:%M") %>
</p>

<p>
  <b>Place (場所):</b>
  <%= @schedule.place %>
</p>

<p>
  <b>Title (タイトル):</b>
  <%= @schedule.title %>
</p>

<p>
  <b>Contents (内容):</b>
  <%= @schedule.contents %>
</p>

<p>
  <b>Open flag (公開):</b>
  <%= @schedule.open_flag %>
</p>

<p>
  <b>Register (登録者):</b>
  <%= @schedule.register %>
</p>


<%= link_to '編集', edit_schedule_path(@schedule) %> |
<%= link_to '一覧へ戻る', schedules_path %>
</div>